/**
 * Code Extraction Utilities
 * Extract React code from AI responses and create sandbox URLs
 */

export interface ExtractedCode {
  code: string;
  language: string;
  hasImports: boolean;
  hasExport: boolean;
  isValid: boolean;
}

/**
 * Extract React/TypeScript code from markdown code blocks
 * Supports ```tsx, ```jsx, ```typescript, ```javascript
 */
export function extractReactCode(text: string): ExtractedCode | null {
  // Try different code block patterns
  const patterns = [
    /```tsx\n([\s\S]*?)```/,
    /```jsx\n([\s\S]*?)```/,
    /```typescript\n([\s\S]*?)```/,
    /```javascript\n([\s\S]*?)```/,
    /```ts\n([\s\S]*?)```/,
    /```js\n([\s\S]*?)```/,
  ];

  for (const pattern of patterns) {
    const match = text.match(pattern);
    if (match && match[1]) {
      const code = match[1].trim();

      // Validate code structure
      const hasImports = /import\s+.*from/.test(code);
      const hasExport = /export\s+default/.test(code);
      const isValid = hasImports && hasExport;

      return {
        code,
        language: "typescript",
        hasImports,
        hasExport,
        isValid,
      };
    }
  }

  return null;
}

/**
 * Create a CodeSandbox URL from React code
 * Opens sandbox in new tab with the generated component
 */
export function createCodeSandboxUrl(code: string): string {
  const files = {
    "package.json": {
      content: {
        name: "ai-generated-component",
        version: "1.0.0",
        description: "Component generated by AI",
        main: "index.tsx",
        scripts: {
          start: "react-scripts start",
          build: "react-scripts build",
        },
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          "react-scripts": "5.0.1",
        },
        devDependencies: {
          "@types/react": "^18.2.0",
          "@types/react-dom": "^18.2.0",
          typescript: "^5.0.0",
        },
      },
    },
    "public/index.html": {
      content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>AI Generated Component</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>`,
    },
    "src/App.tsx": {
      content: code,
    },
    "src/index.tsx": {
      content: `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
    },
    "tsconfig.json": {
      content: {
        compilerOptions: {
          target: "es5",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          strict: true,
          forceConsistentCasingInFileNames: true,
          noFallthroughCasesInSwitch: true,
          module: "esnext",
          moduleResolution: "node",
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
        },
        include: ["src"],
      },
    },
  };

  const parameters = {
    files,
  };

  // Compress and encode for CodeSandbox API
  // Use Unicode-safe encoding to handle special characters
  const jsonString = JSON.stringify(parameters);
  const compressed = typeof window !== 'undefined'
    ? btoa(unescape(encodeURIComponent(jsonString)))
    : Buffer.from(jsonString).toString('base64');
  return `https://codesandbox.io/api/v1/sandboxes/define?parameters=${compressed}`;
}

/**
 * Create a StackBlitz URL from React code
 * Alternative to CodeSandbox with instant preview
 */
export function createStackBlitzUrl(code: string, title: string = "AI Component"): string {
  const files = {
    "package.json": JSON.stringify(
      {
        name: "ai-generated-component",
        version: "1.0.0",
        description: title,
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
        },
        devDependencies: {
          "@types/react": "^18.2.0",
          "@types/react-dom": "^18.2.0",
          typescript: "^5.0.0",
          vite: "^4.0.0",
          "@vitejs/plugin-react": "^3.0.0",
        },
        scripts: {
          dev: "vite",
          build: "vite build",
        },
      },
      null,
      2
    ),
    "index.html": `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
    "src/main.tsx": `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
    "src/App.tsx": code,
    "vite.config.ts": `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});`,
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
        },
        include: ["src"],
      },
      null,
      2
    ),
  };

  // Create StackBlitz project
  const project = {
    title,
    description: "Generated by AI",
    template: "node",
    files,
  };

  // Encode for StackBlitz API with Unicode-safe encoding
  const jsonString = JSON.stringify(project);
  const compressed = typeof window !== 'undefined'
    ? btoa(unescape(encodeURIComponent(jsonString)))
    : Buffer.from(jsonString).toString('base64');
  return `https://stackblitz.com/edit/vitejs-vite-${Date.now()}?file=src/App.tsx&embed=1&hideNavigation=1`;
}

/**
 * Validate generated code for common issues
 */
export function validateCode(code: string): {
  isValid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Check for required imports
  if (!code.includes("import React")) {
    errors.push("Missing React import");
  }

  // Check for default export
  if (!code.includes("export default")) {
    errors.push("Missing default export");
  }

  // Check for JSX return
  if (!code.includes("return (") && !code.includes("return(")) {
    warnings.push("Component may not return JSX");
  }

  // Check for Tailwind classes
  if (!code.includes('className="')) {
    warnings.push("No Tailwind classes found - component may not be styled");
  }

  // Check for inline styles (should use Tailwind instead)
  if (code.includes("style={{") || code.includes("style={")) {
    warnings.push("Component uses inline styles - should use Tailwind classes");
  }

  // Check for custom CSS
  if (code.includes("<style") || code.includes("const styles =")) {
    warnings.push("Component uses custom CSS - should use Tailwind classes");
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}

/**
 * Format code for display
 * Adds line numbers and syntax highlighting preparation
 */
export function formatCodeForDisplay(code: string): string {
  return code.trim();
}

/**
 * Extract component name from code
 */
export function extractComponentName(code: string): string {
  const match = code.match(/export\s+default\s+function\s+(\w+)/);
  return match ? match[1] : "Component";
}

/**
 * Create download link for code file
 */
export function createDownloadUrl(code: string, filename: string = "Component.tsx"): string {
  const blob = new Blob([code], { type: "text/typescript" });
  return URL.createObjectURL(blob);
}

/**
 * Copy code to clipboard
 */
export async function copyToClipboard(code: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(code);
    return true;
  } catch (error) {
    console.error("Failed to copy to clipboard:", error);
    return false;
  }
}
